FROM eclipse-temurin:17-jre

# deployment unit
COPY target/service-alarm-config-logger-*.jar /alarmlogger/service-alarm-config-logger-*.jar

CMD ["java", "-jar", "/alarmlogger/service-alarm-config-logger-*.jar"]
